/*
 * Generated by TKLGEN - VersionJun 22 2016
 * Copyright (C) 2013, Thiago Adams (thiago.adams@gmail.com)
 * www.thradams.com
 *
 */
#ifndef PARSER_H
#define PARSER_H


#include "Result.h"
#include "Main.h"

typedef enum 
{
Main_OnError
}Main_Actions;

function Main_Main(Main_Context* ctx) : Result;
const char* Main_Actions_Text(Main_Actions e);



#endif
